version: "3"
services:
    node-app:
        container_name: node-app
        hostname: "node-app"
        build: .
    # Run the caddy server        
    caddy:
        image: caddy/caddy:2.2.1-alpine
        container_name: caddy-service
        restart: unless-stopped
        ports:
            - "4000:80"
            - "5000:443"
        volumes:            
        - $PWD/Caddyfile:/etc/caddy/Caddyfile
        - $PWD/site:/srv
        - caddy_data:/data
        - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: 
